# Site settings
title: Authentic Jazz Weekend 2016
email: sweetheartkorea@gmail.com
url: https://www.authenticjazzweekend.com/2016
baseurl: "/2016"
description: "Authentic Jazz Weekend"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sweetheart Korea

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/events/733032450165139/

# Build settings
markdown: kramdown
permalink: pretty

date_format: "%b %-d, %Y"

disqus-shortname: "ajw2016"
